#!/bin/bash
set -eu

STAGED_GO_FILES=$(git diff --cached --name-only -- '*.go')

if [[ $STAGED_GO_FILES == "" ]]; then
    echo "No Go Files to Update"
else
    just check $STAGED_GO_FILES
    git add $STAGED_GO_FILES
fi
