#!/bin/sh

cat << EOF > $1
# Header: type(scope): subject
# Allowed type: fix, feat, docs, style, refactor, perf, test, build, ci
# Allowed scope: package name
# revert: Header of revereted commit
# Don't capitalise, no period
# No more than 50 chars. #### 50 chars is here: #

# Blank line...

# Body: Use imperative, present tense.
# Include motivation, contrast with previous behaviour
# Wrap at 72 chars. ################################## which is here: #

# Blank line...

# Footer:
# If breaking, begin "BREAKING CHANGE: " and describe justification
# and migration notes
# References to issue numbers, like so...
# Resolves: #154
# See Also: #168, #67

# End of Message
EOF
